version: '3.9'


services:
  ms-gps:
    image: ms-gps
    build: ../ms-gps
    environment:
      NODE_ENV: development
    ports:
      - "8090:8090"


  ms-reward:
    image: ms-reward
    build: ../ms-reward
    environment:
      NODE_ENV: development
    ports:
      - "8092:8092"


  ms-user:
    image: ms-user
    build: ../ms-user
    environment:
      NODE_ENV: development
    ports:
      - "8091:8091"

