version: "3.9"
services:
  ms-gps:
    image: ms-gps
    ports:
      - "8090:8090"
    volumes:
      - .:/ms-gps
    command:
    - run

  ms-reward:
    image: ms-reward
    ports:
      - "8092:8092"
    volumes:
      - .:/ms-reward
    command:
      - run

  ms-user:
    image: ms-user
    ports:
      - "8091:8091"
    volumes:
      - .:/ms-gps
    command:
      - run


